### ISSUE TITLE
APIGateway trigger not showing in Lambda console

### ISSUE THREAD

**Issue by alexandrecanuto** [aws-samples/simple-websockets-chat-app#15]
When I built this sample, the API Gateway trigger integration shows up in Lambda console:
![Captura de Tela 2019-03-08 às 19 04 26](https://user-images.githubusercontent.com/6773794/54058696-6764a780-41d5-11e9-9464-a5045ee00164.png)

When building my own app, **everything works just fine**, but the trigger does not show up in Lambda console:
![Captura de Tela 2019-03-08 às 19 04 05](https://user-images.githubusercontent.com/6773794/54058729-7ea39500-41d5-11e9-99cc-f3747b5ba587.png)

Again, I should point out that my API is working just fine, it's just odd and makes me feel like I might be missing something important.

My template looks pretty much the same (so does the API Gateway route overview in the console):

```
...

ConnectRoute:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId: !Ref RedeChatWSApi
      RouteKey: $connect
      AuthorizationType: NONE
      OperationName: ConnectRoute
      Target: !Join
        - "/"
        - - "integrations"
          - !Ref ConnectInteg
  ConnectInteg:
    Type: AWS::ApiGatewayV2::Integration
    Properties:
      ApiId: !Ref RedeChatWSApi
      Description: Connect integration.
      IntegrationType: AWS_PROXY
      IntegrationUri:
        Fn::Sub:
          arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${OnConnectFunction.Arn}/invocations

...

Outputs:
  OnConnectFunctionArn:
    Description: OnConnect function ARN.
    Value: !GetAtt OnConnectFunction.Arn
```

Thanks for the help. 😀
